<template>
  <div class="space-y-8">
    <div class="flex items-center justify-between">
      <div>
        <h2 class="font-display text-2xl font-bold text-ink">Administrative Reports</h2>
        <p class="text-sm text-ink-soft">Generate and export system data for audit and compliance purposes.</p>
      </div>
      <div class="flex items-center gap-2 text-xs font-bold text-ink-soft bg-surface px-4 py-2 rounded-full border border-gray-100">
         <span class="h-2 w-2 rounded-full bg-brand-green"></span>
         Data Source: Real-time Production DB
      </div>
    </div>

    <!-- Report Types Grid -->
    <div class="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
        <div v-for="report in reportTypes" :key="report.title" class="card-hover p-6 group">
            <div :class="['mb-4 flex h-14 w-14 items-center justify-center rounded-2xl text-2xl shadow-sm transition-transform group-hover:scale-110', report.bgClass]">
                {{ report.icon }}
            </div>
            <h3 class="font-display text-lg font-bold text-ink">{{ report.title }}</h3>
            <p class="mt-2 text-xs leading-relaxed text-ink-soft">{{ report.description }}</p>
            
            <div class="mt-6 flex flex-col gap-2">
                <button class="btn-primary w-full !py-2 text-xs flex items-center justify-center gap-2" :disabled="generating" @click="generateReport(report)">
                    {{ generating === report.id ? 'Processing...' : 'Download CSV' }}
                    <span v-if="generating !== report.id">📥</span>
                </button>
                <div class="flex items-center justify-between text-[10px] uppercase tracking-widest font-bold text-ink-soft/40 px-1 mt-1">
                    <span>Format: CSV / XLSX</span>
                    <span>Last Run: {{ report.lastRun || 'Never' }}</span>
                </div>
            </div>
        </div>
    </div>

    <!-- Data Preview / Recent Exports Section -->
    <div class="card">
        <div class="flex items-center justify-between border-b border-gray-50 px-8 py-5">
            <h3 class="font-display text-lg font-bold text-ink">Exported Files History</h3>
            <span class="text-xs font-bold text-ink-soft italic">Retention: 30 Days</span>
        </div>
        <div class="p-0">
            <div v-if="history.length > 0" class="divide-y divide-gray-50">
                <div v-for="file in history" :key="file.id" class="flex items-center justify-between px-8 py-4 hover:bg-surface transition-colors">
                    <div class="flex items-center gap-4">
                        <div class="h-10 w-10 flex items-center justify-center bg-brand-blue-soft/30 rounded-lg text-lg">📄</div>
                        <div>
                            <div class="text-sm font-bold text-ink">{{ file.name }}</div>
                            <div class="text-[11px] text-ink-soft">{{ file.size }} • Generated by {{ file.actor }}</div>
                        </div>
                    </div>
                    <div class="flex items-center gap-6">
                        <div class="text-right">
                            <div class="text-[11px] font-bold text-ink lowercase">today at 14:22</div>
                            <div class="text-[10px] text-brand-green font-bold uppercase tracking-wider">Available</div>
                        </div>
                        <button class="btn-secondary !px-4 !py-2 !text-xs !bg-white hover:!bg-brand-blue-soft hover:!text-brand-blue">Download</button>
                    </div>
                </div>
            </div>
            <div v-else class="empty-state py-12 border-0">
                No recent exports found. Start by generating a report above.
            </div>
        </div>
    </div>

    <!-- Advanced Configuration -->
    <div class="card bg-surface/50 border-dashed p-6 border-gray-300">
        <h4 class="mb-4 text-xs font-bold uppercase tracking-widest text-ink-soft">Advanced Export Settings</h4>
        <div class="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-4">
            <div>
                <label class="field-label">Date Range</label>
                <select class="input-field mt-1">
                    <option>Last 7 Days</option>
                    <option>Last 30 Days</option>
                    <option>This Quarter</option>
                    <option>Custom Range</option>
                </select>
            </div>
            <div>
                <label class="field-label">Detail Level</label>
                <select class="input-field mt-1">
                    <option>Summary (Light)</option>
                    <option>Detailed (Heavy)</option>
                    <option>Archive Grade</option>
                </select>
            </div>
            <div class="flex items-end">
                <label class="flex items-center gap-3 cursor-pointer">
                    <input type="checkbox" checked class="h-4 w-4 rounded border-gray-300 text-brand-blue focus:ring-brand-blue" />
                    <span class="text-sm font-semibold text-ink">Include Anonymized Metadata</span>
                </label>
            </div>
        </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const generating = ref<string | null>(null)

const reportTypes = [
    { id: 'accounts', title: 'User Account Registry', icon: '👥', bgClass: 'bg-blue-50 text-brand-blue', description: 'Complete list of all teachers, students, and admins with their current status and contact info.', lastRun: '2 days ago' },
    { id: 'activity', title: 'Activity Engagement', icon: '📈', bgClass: 'bg-teal-50 text-brand-teal', description: 'Metrics on student engagement, activity completions, and system usage over a specified period.', lastRun: 'Today' },
    { id: 'audit', title: 'System Security Audit', icon: '🛡️', bgClass: 'bg-violet-50 text-brand-violet', description: 'Comprehensive log of sensitive administrative actions, login attempts, and status changes.', lastRun: null },
    { id: 'content', title: 'Curriculum Inventory', icon: '📚', bgClass: 'bg-amber-50 text-brand-amber', description: 'Snapshot of all active modules, quizzes, and learning materials across the platform.', lastRun: '1 week ago' },
    { id: 'compliance', title: 'Access Logs (Compliance)', icon: '⚖️', bgClass: 'bg-rose-50 text-brand-rose', description: 'Immutable log of system entry and exit points for regulatory compliance requirements.', lastRun: null }
]

const history = ref([
    { id: 1, name: 'teacher_registry_2026-07-04.csv', size: '1.2 MB', actor: 'Admin (Denmhar)' },
    { id: 2, name: 'student_engagement_q2.xlsx', size: '4.8 MB', actor: 'Admin (Denmhar)' }
])

function generateReport(report: any) {
    generating.value = report.id
    // Mock generation delay
    setTimeout(() => {
        generating.value = null
        alert(`Successfully generated report: ${report.title}`)
    }, 2000)
}
</script>

<style scoped>
.shadow-card {
  box-shadow: 0 4px 20px rgba(67, 97, 238, 0.08);
}
</style>
